<?php

use App\Http\Controllers\Admin\AdminBrokerController;
use App\Http\Controllers\Admin\AdminBrokerPlanController;
use App\Http\Controllers\Admin\AdminBrokerSettingsController;
use App\Http\Controllers\Admin\BusinessSettingsController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\CmsPageController;
use App\Http\Controllers\Admin\DataTransferController;
use App\Http\Controllers\Admin\HomeFeatureController;
use App\Http\Controllers\Admin\HowItWorksController;
use App\Http\Controllers\Admin\PagesController;
use App\Http\Controllers\Admin\PropertyCategoryController;
use App\Http\Controllers\Admin\PropertyTypeController;
use App\Http\Controllers\Admin\RejectionReasonController;
use App\Http\Controllers\Admin\RoomOptionController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PlanController;
use Illuminate\Support\Facades\Route;

Route::get('/portal/access-check', [\App\Http\Controllers\Auth\AuthenticatedSessionController::class, 'adminAccess'])
    ->name('admin.login-access');
Route::post('/portal/access-check', [\App\Http\Controllers\Auth\AuthenticatedSessionController::class, 'adminAuthenticate'])
    ->middleware('throttle:strict_login')->name('admin.login.submit');

Route::middleware(['auth', 'role:admin', 'admin.permission', 'admin.activity'])
    ->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');
    Route::get('/staff', [\App\Http\Controllers\Admin\AdminStaffController::class, 'index'])->name('staff.index');
    Route::post('/staff', [\App\Http\Controllers\Admin\AdminStaffController::class, 'store'])->name('staff.store');
    Route::put('/staff/{staff}', [\App\Http\Controllers\Admin\AdminStaffController::class, 'update'])->name('staff.update');
    Route::post('/staff/{staff}/toggle', [\App\Http\Controllers\Admin\AdminStaffController::class, 'toggle'])->name('staff.toggle');
    Route::delete('/staff/{staff}', [\App\Http\Controllers\Admin\AdminStaffController::class, 'destroy'])->name('staff.destroy');
    Route::post('/staff/{id}/restore', [\App\Http\Controllers\Admin\AdminStaffController::class, 'restore'])->name('staff.restore');
    Route::get('/roles', [\App\Http\Controllers\Admin\AdminRoleController::class, 'index'])->name('roles.index');
    Route::get('/roles/create', [\App\Http\Controllers\Admin\AdminRoleController::class, 'create'])->name('roles.create');
    Route::post('/roles', [\App\Http\Controllers\Admin\AdminRoleController::class, 'store'])->name('roles.store');
    Route::put('/roles/{role}', [\App\Http\Controllers\Admin\AdminRoleController::class, 'update'])->name('roles.update');
    Route::delete('/roles/{role}', [\App\Http\Controllers\Admin\AdminRoleController::class, 'destroy'])->name('roles.destroy');
    Route::get('/activity-logs', [\App\Http\Controllers\Admin\AdminActivityController::class, 'index'])->name('activity.index');
    Route::delete('/activity-logs/bulk', [\App\Http\Controllers\Admin\AdminActivityController::class, 'bulkDestroy'])->name('activity.bulk-destroy');
    Route::delete('/activity-logs/filtered', [\App\Http\Controllers\Admin\AdminActivityController::class, 'destroyFiltered'])->name('activity.destroy-filtered');
    Route::delete('/activity-logs/{activityLog}', [\App\Http\Controllers\Admin\AdminActivityController::class, 'destroy'])->name('activity.destroy');

    Route::get('/notifications', [\App\Http\Controllers\Admin\AdminNotificationController::class, 'index'])->name('notifications.index');
    Route::match(['get', 'post'], '/notifications/{notification}/read', [\App\Http\Controllers\Admin\AdminNotificationController::class, 'markRead'])->name('notifications.markRead');
    Route::post('/notifications/read-all', [\App\Http\Controllers\Admin\AdminNotificationController::class, 'markAllRead'])->name('notifications.markAllRead');
    Route::get('/notifications/unread-count', [\App\Http\Controllers\Admin\AdminNotificationController::class, 'unreadCount'])->name('notifications.unreadCount');
    Route::delete('/notifications/{notification}', [\App\Http\Controllers\Admin\AdminNotificationController::class, 'destroy'])->name('notifications.destroy');
    Route::post('/notifications/clear-all', [\App\Http\Controllers\Admin\AdminNotificationController::class, 'clearAll'])->name('notifications.clearAll');
    Route::get('/broadcast', [\App\Http\Controllers\Admin\AdminBroadcastController::class, 'index'])->name('broadcast.index');
    Route::post('/broadcast/send', [\App\Http\Controllers\Admin\AdminBroadcastController::class, 'send'])->name('broadcast.send');

    Route::patch('blogs/{blog}/toggle-status', [\App\Http\Controllers\Admin\BlogController::class, 'toggleStatus'])->name('blogs.toggle-status');
    Route::resource('blogs', \App\Http\Controllers\Admin\BlogController::class)->except(['show']);
    Route::get('/settings', [BusinessSettingsController::class, 'index'])->name('settings');
    Route::get('/maintenance', [BusinessSettingsController::class, 'maintenance'])->name('maintenance');
    Route::post('/maintenance', [BusinessSettingsController::class, 'updateMaintenance'])->name('maintenance.update');
    Route::get('/data-maintenance', [\App\Http\Controllers\Admin\DataMaintenanceController::class, 'index'])->name('data-maintenance.index');
    Route::post('/data-maintenance/backup', [\App\Http\Controllers\Admin\DataMaintenanceController::class, 'backup'])->name('data-maintenance.backup');
    Route::put('/data-maintenance/retention', [\App\Http\Controllers\Admin\DataMaintenanceController::class, 'update'])->name('data-maintenance.update');
    Route::post('/data-maintenance/cleanup', [\App\Http\Controllers\Admin\DataMaintenanceController::class, 'cleanup'])->name('data-maintenance.cleanup');
    Route::get('/data-tools', [DataTransferController::class, 'index'])->name('data-tools.index');
    Route::get('/data-tools/export/{dataset}', [DataTransferController::class, 'export'])->name('data-tools.export');
    Route::get('/data-tools/template/{dataset}', [DataTransferController::class, 'template'])->name('data-tools.template');
    Route::post('/data-tools/import/{dataset}', [DataTransferController::class, 'import'])->name('data-tools.import');
    Route::get('/data-tools/report/{dataset}', [DataTransferController::class, 'report'])->name('data-tools.report');
    Route::get('/cities', [CityController::class, 'index'])->name('cities.index');
    Route::get('/cities/create', [CityController::class, 'create'])->name('cities.create');
    Route::post('/cities', [CityController::class, 'store'])->name('cities.store');
    Route::get('/cities/{city}/edit', [CityController::class, 'edit'])->name('cities.edit');
    Route::put('/cities/{city}', [CityController::class, 'update'])->name('cities.update');
    Route::delete('/cities/{city}', [CityController::class, 'destroy'])->name('cities.destroy');
    Route::post('/settings', [BusinessSettingsController::class, 'update'])->name('settings.update');
    Route::post('/settings/store', [BusinessSettingsController::class, 'store'])->name('settings.store');
    Route::post('/settings/ping', [BusinessSettingsController::class, 'pingSearchEngines'])->name('settings.ping');
    Route::patch('cms-pages/{cmsPage}/toggle-status', [CmsPageController::class, 'toggleStatus'])->name('cms-pages.toggle-status');
    Route::resource('cms-pages', CmsPageController::class)->except(['show']);
    Route::get('pages/faq', [PagesController::class, 'faq'])->name('pages.faq');
    Route::put('pages/faq', [PagesController::class, 'updateFaq'])->name('pages.faq.update');
    Route::patch('home-features/{homeFeature}/toggle-status', [HomeFeatureController::class, 'toggleStatus'])->name('home-features.toggle-status');
    Route::resource('home-features', HomeFeatureController::class)->except(['show']);
    Route::get('how-it-works', [HowItWorksController::class, 'index'])->name('how-it-works.index');
    Route::put('how-it-works/settings', [HowItWorksController::class, 'updateSettings'])->name('how-it-works.settings');
    Route::get('how-it-works/items/create', [HowItWorksController::class, 'create'])->name('how-it-works.items.create');
    Route::post('how-it-works/items', [HowItWorksController::class, 'store'])->name('how-it-works.items.store');
    Route::get('how-it-works/items/{item}/edit', [HowItWorksController::class, 'edit'])->name('how-it-works.items.edit');
    Route::put('how-it-works/items/{item}', [HowItWorksController::class, 'update'])->name('how-it-works.items.update');
    Route::delete('how-it-works/items/{item}', [HowItWorksController::class, 'destroy'])->name('how-it-works.items.destroy');
    Route::patch('how-it-works/items/{item}/toggle-status', [HowItWorksController::class, 'toggleStatus'])->name('how-it-works.items.toggle-status');
    Route::patch('testimonials/{testimonial}/toggle-status', [TestimonialController::class, 'toggleStatus'])->name('testimonials.toggle-status');
    Route::resource('testimonials', TestimonialController::class)->except(['show']);
    Route::resource('room-options', RoomOptionController::class)->except(['show']);
    Route::patch('room-options/{roomOption}/toggle-status', [RoomOptionController::class, 'toggleStatus'])->name('room-options.toggle-status');
    Route::resource('property-types', PropertyTypeController::class)->except(['show']);
    Route::patch('property-types/{propertyType}/toggle-status', [PropertyTypeController::class, 'toggleStatus'])->name('property-types.toggle-status');
    Route::resource('property-categories', PropertyCategoryController::class)->except(['show']);
    Route::patch('property-categories/{propertyCategory}/toggle-status', [PropertyCategoryController::class, 'toggleStatus'])->name('property-categories.toggle-status');
    Route::patch('rejection-reasons/{rejectionReason}/toggle-status', [RejectionReasonController::class, 'toggleStatus'])->name('rejection-reasons.toggle-status');
    Route::patch('cities/{city}/toggle-status', [CityController::class, 'toggleStatus'])->name('cities.toggle-status');
    Route::resource('plans', PlanController::class)->except(['show']);
    Route::post('/plans/{plan}/toggle-active', [PlanController::class, 'toggleActive'])->name('plans.toggleActive');
    Route::resource('offers', \App\Http\Controllers\Admin\OfferController::class)->except(['show']);
    Route::post('/offers/{offer}/toggle-active', [\App\Http\Controllers\Admin\OfferController::class, 'toggleActive'])->name('offers.toggleActive');

    Route::get('/members', [AdminController::class, 'member360'])->name('members.index');
    Route::get('/users', [AdminController::class, 'users'])->name('users');
    Route::get('/users/create', [AdminController::class, 'createUser'])->name('users.create');
    Route::post('/users', [AdminController::class, 'storeUser'])->name('users.store');
    Route::get('/users/{user}', [AdminController::class, 'userDetail'])->name('users.detail');
    Route::get('/users/{user}/edit', [AdminController::class, 'editUser'])->name('users.edit');
    Route::put('/users/{user}', [AdminController::class, 'updateUser'])->name('users.update');
    Route::delete('/users/{user}', [AdminController::class, 'destroyUser'])->name('users.destroy');
    Route::post('/users/{user}/toggle-block', [AdminController::class, 'toggleBlock'])->name('users.toggleBlock');
    Route::put('/members/{user}/notes', [AdminController::class, 'updateMemberNotes'])->name('members.notes');
    Route::post('/members/{user}/send-direct-message', [AdminController::class, 'sendDirectMessage'])->name('members.sendDirectMessage');
    Route::post('/members/{user}/restore', [AdminController::class, 'restoreMember'])->name('members.restore');
    Route::get('/owners', [AdminController::class, 'owners'])->name('owners');
    Route::get('/owners/create', [AdminController::class, 'createOwner'])->name('owners.create');
    Route::post('/owners', [AdminController::class, 'storeOwner'])->name('owners.store');
    Route::get('/owners/{owner}', [AdminController::class, 'ownerDetail'])->name('owners.detail');
    Route::get('/owners/{owner}/edit', [AdminController::class, 'editOwner'])->name('owners.edit');
    Route::put('/owners/{owner}', [AdminController::class, 'updateOwner'])->name('owners.update');
    Route::delete('/owners/{owner}', [AdminController::class, 'destroyOwner'])->name('owners.destroy');
    Route::post('/owners/{user}/toggle-block', [AdminController::class, 'toggleBlock'])->name('owners.toggleBlock');
    Route::post('/owners/{owner}/remind-kyc', [AdminController::class, 'remindKyc'])->name('owners.remind-kyc');
    Route::get('/brokers', [AdminBrokerController::class, 'index'])->name('brokers.index');
    Route::get('/broker-reviews', [AdminBrokerController::class, 'reviewsIndex'])->name('broker-reviews.index');
    Route::get('/brokers/{broker}', [AdminBrokerController::class, 'show'])->name('brokers.show');
    Route::post('/brokers/{broker}/approve', [AdminBrokerController::class, 'approve'])->name('brokers.approve');
    Route::post('/brokers/{broker}/reject', [AdminBrokerController::class, 'reject'])->name('brokers.reject');
    Route::post('/brokers/{broker}/suspend', [AdminBrokerController::class, 'suspend'])->name('brokers.suspend');
    Route::post('/brokers/{broker}/activate', [AdminBrokerController::class, 'activate'])->name('brokers.activate');
    Route::post('/brokers/{broker}/toggle-featured', [AdminBrokerController::class, 'toggleFeatured'])->name('brokers.toggle-featured');
    Route::post('/brokers/{broker}/set-featured', [AdminBrokerController::class, 'setFeaturedDuration'])->name('brokers.set-featured');
    Route::post('/brokers/{broker}/reviews/{review}/toggle-status', [AdminBrokerController::class, 'toggleReviewStatus'])->name('brokers.reviews.toggle-status');
    Route::delete('/brokers/{broker}/reviews/{review}', [AdminBrokerController::class, 'destroyReview'])->name('brokers.reviews.destroy');
    Route::post('/broker-reviews/{review}/toggle-status', [AdminBrokerController::class, 'toggleReviewStatusDirect'])->name('broker-reviews.toggle-status');
    Route::delete('/broker-reviews/{review}', [AdminBrokerController::class, 'destroyReviewDirect'])->name('broker-reviews.destroy');
    Route::delete('/brokers/{broker}', [AdminBrokerController::class, 'destroy'])->name('brokers.destroy');
    Route::get('/broker-settings', [AdminBrokerSettingsController::class, 'index'])->name('broker-settings.index');
    Route::post('/broker-settings', [AdminBrokerSettingsController::class, 'update'])->name('broker-settings.update');
    Route::resource('broker-plans', AdminBrokerPlanController::class)->except(['show']);
    Route::post('/broker-plans/{brokerPlan}/toggle-active', [AdminBrokerPlanController::class, 'toggleActive'])->name('broker-plans.toggleActive');
    Route::get('/reports', [AdminController::class, 'reports'])->name('reports');
    Route::get('/all-rooms', [AdminController::class, 'rooms'])->name('all-rooms');
    Route::get('/payments-index', [AdminController::class, 'paymentsIndex'])->name('payments.index');
    Route::get('/city-alerts', [AdminController::class, 'cityAlerts'])->name('city-alerts.index');
    Route::delete('/city-alerts/{alert}', [AdminController::class, 'deleteCityAlert'])->name('city-alerts.destroy');
    Route::get('/subscribers', [\App\Http\Controllers\Admin\SubscriberController::class, 'index'])->name('subscribers.index');
    Route::delete('/subscribers/{subscriber}', [\App\Http\Controllers\Admin\SubscriberController::class, 'destroy'])->name('subscribers.destroy');
    Route::get('/contact-messages', [AdminController::class, 'contactMessages'])->name('contact-messages.index');
    Route::post('/contact-messages/{id}/read', [AdminController::class, 'markMessageAsRead'])->name('contact-messages.read');
    Route::delete('/contact-messages/{id}', [AdminController::class, 'deleteContactMessage'])->name('contact-messages.destroy');
    Route::get('/complaints', [\App\Http\Controllers\Admin\ComplaintController::class, 'index'])->name('complaints.index');
    Route::get('/complaints/{complaint}', [\App\Http\Controllers\Admin\ComplaintController::class, 'show'])->name('complaints.show');
    Route::put('/complaints/{complaint}', [\App\Http\Controllers\Admin\ComplaintController::class, 'update'])->name('complaints.update');
    Route::post('/complaints/{complaint}/assign', [\App\Http\Controllers\Admin\ComplaintController::class, 'assign'])->name('complaints.assign');
    Route::post('/complaints/{complaint}/reply', [\App\Http\Controllers\Admin\ComplaintController::class, 'reply'])->name('complaints.reply');
    Route::post('/complaints/{complaint}/reopen', [\App\Http\Controllers\Admin\ComplaintController::class, 'reopen'])->name('complaints.reopen');
    Route::resource('rejection-reasons', RejectionReasonController::class)->except(['show']);
    Route::get('rooms', [AdminController::class, 'rooms'])->name('rooms.list');
    Route::get('rooms/create', [AdminController::class, 'createRoom'])->name('rooms.create');
    Route::post('rooms/store', [AdminController::class, 'storeRoom'])->name('rooms.store');
    Route::get('rooms/{room}', [AdminController::class, 'showRoom'])->name('rooms.show');
    Route::get('rooms/{room}/edit', [AdminController::class, 'editRoom'])->name('rooms.edit');
    Route::put('rooms/{room}/update', [AdminController::class, 'updateRoom'])->name('rooms.update');
    Route::post('/rooms/{room}/approve', [AdminController::class, 'approveRoom'])->name('rooms.approve');
    Route::post('/rooms/{room}/reject', [AdminController::class, 'rejectRoom'])->name('rooms.reject');
    Route::patch('/rooms/{room}/toggle-status', [AdminController::class, 'toggleRoomStatus'])->name('rooms.toggle-status');
    Route::post('rooms/bulk-action', [AdminController::class, 'bulkRooms'])->name('rooms.bulk');
    Route::delete('rooms/{room}', [AdminController::class, 'deleteRoom'])->name('rooms.destroy');
    Route::get('/analytics', [\App\Http\Controllers\Admin\SearchAnalyticsController::class, 'index'])->name('analytics');
    Route::delete('/analytics/logs/all', [\App\Http\Controllers\Admin\SearchAnalyticsController::class, 'destroyAll'])->name('analytics.logs.all');
    Route::delete('/analytics/logs/range', [\App\Http\Controllers\Admin\SearchAnalyticsController::class, 'destroyRange'])->name('analytics.logs.range');
    Route::delete('/analytics/logs/{searchLog}', [\App\Http\Controllers\Admin\SearchAnalyticsController::class, 'destroy'])->name('analytics.logs.destroy');
    Route::post('/pages/upload-image', [PagesController::class, 'uploadImage'])->name('pages.upload-image');
    Route::get('/pages/{key}', [CmsPageController::class, 'legacy'])
        ->where('key', 'about|careers|how-it-works|safety-tips|owner-guidelines|user-guidelines|terms|condition|privacy|contact|faq')
        ->name('pages.legacy');
});
